# Travis-CI configuration file for Plinth

language: python
sudo: false
python:
  - "3.2"
  - "3.4"
  - "3.5"

# Command to install dependencies
install:
  - pip install coverage==3.7
  - pip install -r requirements.txt

# Command to run tests
script: python3 setup.py test

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.oftc.net#freedombox"
    on_success: always
    on_failure: always
